martensonbj/little_shop

.byebug_history
app/controllers/categories_controller.rb
app/models/category.rb
app/views/categories/show.html.erb
config/routes.rb
db/migrate/20160112012622_add_slug_to_categories.rb
db/schema.rb
test/factories/factories.rb
test/integration/user_can_visit_items_page_test.rb
test/integration/user_sees_items_by_category_test.rb
test/test_helper.rb

Added vanity url functionality, with all tests passing.

3 browsing items by category

---

.byebug_history
app/assets/stylesheets/application.css
app/controllers/application_controller.rb
app/controllers/cart_items_controller.rb
app/controllers/items_controller.rb
app/models/cart.rb
app/models/item.rb
app/views/cart_items/index.html.erb
app/views/home/index.html.erb
app/views/items/show.html.erb
app/views/layouts/_navbar.html.erb
app/views/layouts/application.html.erb
app/views/layouts/home.html.erb
app/views/shared/_item_card.html.erb
config/routes.rb
data.txt
db/migrate/20160112182216_add_price_and_description_to_items.rb
db/schema.rb
test/factories/factories.rb
test/integration/guest_can_add_item_to_cart_test.rb

Implements the shopping cart functionality for the site.

Shopping cart

---

.byebug_history
Gemfile
Gemfile.lock
app/assets/stylesheets/application.css
app/controllers/cart_items_controller.rb
app/models/cart.rb
app/views/cart_items/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb
test/integration/user_removes_item_from_cart_test.rb
test/test_helper.rb

Each item in the card has a 'Remove' link next to it. When clicked, the item is removed from the cart, including removing it from the session. If there is more than one of the item (for example, two of the same painting) then BOTH will be removed. Also includes a green flash message letting the user know that the item has been successfully removed from their cart. The flash message includes a link to the item's show page so the user can easily go back to that item and re-add it if they wish.
closes #12

12 remove item from cart

---

app/controllers/orders_controller.rb
app/controllers/sessions_controller.rb
app/models/item.rb
app/models/order.rb
app/models/order_item.rb
app/models/user.rb
app/views/cart_items/index.html.erb
app/views/orders/index.html.erb
app/views/sessions/new.html.erb
app/views/users/new.html.erb
config/routes.rb
db/migrate/20160113211626_create_orders.rb
db/migrate/20160113214301_create_order_items.rb
db/schema.rb
test/factories/factories.rb
test/factories/users.rb
test/integration/user_can_visit_items_page_test.rb
test/integration/user_checks_out_from_cart_test.rb
test/integration/user_sees_browse_button_on_landing_page_test.rb
test/models/order_item_test.rb
test/models/order_test.rb
test/test_helper.rb

[WIP] User can checkout an order after adding items to a cart. Style on '/orders' page still needs work. Fixing Hound complaints and rebasing.

17 checking out closes #17

---

app/controllers/sessions_controller.rb

Added additional functionality to the sessions controller. When you're on the login page and enter invalid credentials there is now a link in the flash message that asks if you want to create a new account. 
All tests still passing.

Add link to create new account in flash message

---

app/assets/stylesheets/application.css
app/controllers/orders_controller.rb
app/models/cart.rb
app/views/items/show.html.erb
app/views/layouts/_navbar.html.erb
app/views/orders/_order_card.html.erb
app/views/orders/index.html.erb
app/views/orders/show.html.erb
test/integration/user_cannot_checkout_with_zero_items_test.rb
test/integration/user_sees_details_for_past_orders_test.rb

I added some style to the orders show and index pages. I also pulled the show page code out into a partial called _order_card.html.erb which is in the orders views folder, but I had issues making the variables translate  to the orders_index page.
Additional issues we should address: Something is going on with the cart.rb file when calculating the subtotal of individual items. On both the index and show pages if I add certain pictures I'm getting nil back for the inject method. Germany, Shanghai, Aurora, and Darkness seem to be safe. 
I also think we should add a "delete order" button on the orders index page, or set up a catch method for if the cart is empty -  it's letting me create orders with nothing in them when I click "checkout".

Style order index and show pages

---

app/models/artist.rb
app/models/category.rb
app/models/user.rb
test/models/artist_test.rb
test/models/category_test.rb
test/models/item_test.rb
test/models/user_test.rb
test/test_helper.rb

Added these test. Shout out to Dan for helping configure Shoulda-matchers! All tests pass!

closes #25 Add model test for user and artist

---

app/assets/stylesheets/application.css
app/views/layouts/_head.html.erb
app/views/layouts/_navbar.html.erb
app/views/layouts/application.html.erb
app/views/layouts/home.html.erb

Created a functional side nav for mobile sized devices. Moved logo to center of page when viewport is below 990px. 
Also made a partial for the header.

Closes #18 - Add side mobile nav

---

app/models/user.rb
db/migrate/20160114222006_add_role_to_users.rb
db/schema.rb

Updates the schema with a new migration so the users table has a role.
Role = 0 default user
Role = 1 artist
Role = 2 admin

Add user role to users table

---

app/controllers/orders_controller.rb
app/models/cart.rb
app/models/order_creator.rb
app/views/orders/index.html.erb

Adds a PORO named OrderCreator to handle creating an order and adding items to the order_items table. Also cleans up the cart clear method since we weren't actually calling it before. Turns out we had just been calling clear on the contents directly, so now we are actually using the method we wrote.

Closes #56 Add OrderCreator PORO to move logic

---

app/assets/stylesheets/application.css
app/views/home/index.html.erb

Reformatted the links on the homepage so that the anchor tags are using display:block, now the entire button is clickable, not just the text. 
Also refactored the button styling so the css is not repeated over multiple classes. Still need to make it more dynamic.

Restyle buttons on homepage

---

app/controllers/artists_controller.rb
app/models/user.rb
app/views/artists/index.html.erb
app/views/categories/index.html.erb
app/views/home/index.html.erb
app/views/layouts/_navbar.html.erb
config/routes.rb
test/integration/guest_can_view_items_sorted_by_artist_test.rb

Creates an ArtistsController with an index view that is very similar to the categories controller index view. The magic happens on the User class where I created a scope 'artists' to only pull users that are artists. Also added a new route for the artists index. Links up the navbar and homepage buttons to this new page. We probably want to create an artist show page (similar to the category show page) next.

Browse items by artist

---

app/controllers/admin/items_controller.rb
app/controllers/categories_controller.rb
app/models/item.rb
app/views/admin/items/new.html.erb
app/views/admin/users/show.html.erb
app/views/layouts/_head.html.erb
app/views/layouts/_navbar.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/seeds.rb
test/integration/admin_user_creates_item_test.rb
test/models/item_test.rb

Admin can choose artist and category while creating item.
Also added a javascript overwrite in layout for materialize.
This allowed me to show the drop bars in new_admin_item_path.

closes #76 Add create item function for admin

---

app/controllers/admin/items_controller.rb
app/models/item.rb
app/views/admin/items/_form.html.erb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb
app/views/admin/users/show.html.erb
app/views/shared/_item_card.html.erb
config/routes.rb
db/migrate/20160116203406_add_status_to_items.rb
db/schema.rb
test/integration/admin_can_edit_any_item_test.rb
test/integration/admin_can_view_listing_of_items_test.rb
test/integration/admin_user_creates_item_test.rb

Admin can edit any item. The pathway still needs to be discussed to how he gets to the edit page. Though the admin could, with an item id, go direction to the edit page and change it.

closes #78, closes #77 admin can edit/view item

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/admin/items/_form.html.erb
app/views/admin/items/edit.html.erb
app/views/admin/users/show.html.erb
app/views/shared/_user_info.html.erb
app/views/users/_form.html.erb
app/views/users/edit.html.erb
app/views/users/new.html.erb
app/views/users/show.html.erb
config/routes.rb
db/migrate/20160116212300_add_address_to_users.rb
db/schema.rb
db/seeds.rb
test/factories/factories.rb
test/integration/admin_modify_user_data_test.rb
test/integration/guest_creates_login_with_incorrect_creditials_test.rb
test/integration/user_can_create_account_test.rb
test/integration/user_can_edit_their_info_test.rb
test/models/user_test.rb

Users can edit their own information, but can't access other users information. Also added new migrations to user: Email, street, city, state, zipcode.

closes #73 admin can not modify user info

---

app/models/order.rb
db/migrate/20160116233135_add_status_to_orders.rb
db/schema.rb

Adds the 'status' column to the orders table

Add order status to database

---

app/controllers/admin/items_controller.rb
app/controllers/application_controller.rb
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/views/items/_form.html.erb
app/views/items/edit.html.erb
app/views/items/new.html.erb
app/views/layouts/_navbar.html.erb
app/views/orders/index.html.erb
app/views/shared/_item_card.html.erb
app/views/shared/_item_show.html.erb
app/views/users/_form.html.erb
app/views/users/show.html.erb
config/routes.rb
test/integration/admin_modify_user_data_test.rb
test/integration/artist_can_add_an_item_test.rb
test/integration/artist_can_edit_an_existing_item_test.rb
test/integration/guest_can_create_an_artist_account_test.rb
test/integration/user_can_create_account_test.rb

Lots of artist functionality!!
- Guests signing up for a new account can select "artist" to be an artist
- From the user dashboard, as an artist, I can see "View My Items" and "Add New Item"
- For each piece of art that is mine, I can see the "Edit" button, but I can't see this for any other artist's art.
- An artist can only create art for themselves, and can only edit their own art
I added a lot of sad-path tests for this functionality and had to add a new helper method in order to be able to determine if item being displayed was for the CURRENT artist or not. This means there are now multiple before actions going on in the items_controller.rb file.
Also closes #115 
Also closes #116

closes #112 create artist account

---

app/assets/stylesheets/application.css
app/controllers/admin/items_controller.rb
app/controllers/items_controller.rb
app/views/shared/_item_card.html.erb
app/views/shared/_item_show.html.erb
config/routes.rb
test/integration/admin_can_delete_any_existing_item_test.rb
test/integration/artist_can_delete_their_items_test.rb

[WIP] Added to item show page a button to delete if the current_user is admin or it belongs to the user.

Closes #127 Add delete abilities for items to artist and admin

---

app/assets/javascripts/filter.js
app/assets/stylesheets/application.css
app/views/admin/orders/index.html.erb
app/views/artists/index.html.erb
app/views/categories/index.html.erb
app/views/layouts/_head.html.erb
app/views/layouts/application.html.erb

From the "Browse by Artist" page you can now filter by artist, and from the "Browse by Category" page you can now filter by category. Admin can also filter the orders by order status now.
This is NOT TESTED because it is written with jQuery and Rachel said we will hate our lives if we try to run jQuery with capybara. I manually tested all of this instead.

Closes #107, #118 Filtering Capability

---

app/assets/stylesheets/application.css
app/views/admin/orders/index.html.erb

This is styling for the admin order views

Closes #119 Admin order view was styled

---

app/controllers/admin/items_controller.rb
app/controllers/artists_controller.rb
app/controllers/categories_controller.rb
app/controllers/home_controller.rb
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/models/category.rb
test/factories/factories.rb
test/integration/admin_can_delete_any_existing_item_test.rb
test/integration/admin_can_edit_any_item_test.rb
test/integration/admin_user_creates_item_test.rb
test/integration/artist_can_add_an_item_test.rb
test/integration/artist_can_delete_their_items_test.rb
test/integration/artist_can_edit_an_existing_item_test.rb
test/integration/guest_cannot_view_registered_user_dashboard_test.rb
test/integration/user_can_edit_their_info_test.rb
test/models/category_test.rb
test/models/item_test.rb
test/models/order_test.rb
test/models/user_test.rb

Using the SimpleCov coverage index.html file, I tracked down all the lines of code we weren't hitting with sad path tests and added tests for those. We now have 100% test coverage on this branch!

General refactoring - Test Coverage 100%
